# Week 1 — BRFSS data check

In [1]:
import zipfile
from pathlib import Path
import pandas as pd
from IPython.display import display


zip_path = "csv.zip"

with zipfile.ZipFile(zip_path) as z:
    files = {Path(name).name: name for name in z.namelist()
             if name.lower().endswith(".csv")}

years = range(2005, 2025)

## Read files

In [3]:
# Store summaries
overview = []
missing_rows = []
category_rows = []
columns_by_year = {}

features_to_check = [
    "diabetes", "income_00", "income_01", "income_level_00",
    "income_level_01", "race_00", "employment_status_00",
    "has_personal_doctor_00", "high_bp_00", "high_cholesterol_00"
]

with zipfile.ZipFile(zip_path) as z:
    for year in years:
        filename = files[f"DATASET_{year}.csv"]
        df = pd.read_csv(z.open(filename), low_memory=False)
        columns_by_year[year] = set(df.columns)
        overview.append({"year": year, "rows": len(df), "columns": len(df.columns)})

        # A missing percentage is computed
        for feature in df.columns:
            count = int(df[feature].isna().sum())
            missing_rows.append({"year": year, "feature": feature,
                                 "missing_count": count,
                                 "missing_pct": round(100 * count / len(df), 2)})

         # Save category counts, including missing
        for feature in features_to_check:
            if feature in df.columns:
                for value, count in df[feature].value_counts(dropna=False).items():
                    category_rows.append({"year": year, "feature": feature,
                                          "value": "<missing>" if pd.isna(value) else str(value),
                                          "count": int(count)})

overview = pd.DataFrame(overview)
missing = pd.DataFrame(missing_rows)
categories = pd.DataFrame(category_rows)
display(overview)
del df

    year    rows  columns
0   2005  355446       33
1   2006  354497       31
2   2007  429942       33
3   2008  412898       31
4   2009  431636       33
5   2010  449156       31
6   2011  503846       33
7   2012  473243       31
8   2013  490368       33
9   2014  461879       31
10  2015  439881       33
11  2016  483230       31
12  2017  447952       33
13  2018  434232       31
14  2019  416661       33
15  2020  399050       31
16  2021  437250       33
17  2022  442670       31
18  2023  431746       33
19  2024  454774       31

In [21]:
print("Between 10 to 20 Percent Missing Overview")
missing[missing.missing_pct.between(10, 20)

Between 10 to 20 Percent Missing Overview

     year              feature  missing_count  missing_pct
12   2005      income_level_00          48611        13.68
13   2005            income_00          48611        13.68
24   2005  high_cholesterol_00          66368        18.67
45   2006      income_level_00          49751        14.03
46   2006            income_00          49751        14.03
76   2007      income_level_00          58839        13.69
77   2007            income_00          58839        13.69
88   2007  high_cholesterol_00          67097        15.61
109  2008      income_level_00          53464        12.95
110  2008            income_00          53464        12.95
140  2009      income_level_00          58361        13.52
141  2009            income_00          58361        13.52
152  2009  high_cholesterol_00          58581        13.57
173  2010      income_level_00          64175        14.29
174  2010            income_00          64175        14.29
204  2011      income_level_00          73196        14.53
205  2011            income_00          73196        14.53
216  2011  high_cholesterol_00          73936        14.67
237  2012      income_level_00          66354        14.02
238  2012            income_00          66354        14.02
268  2013      income_level_00          71010        14.48
269  2013            income_00          71010        14.48
280  2013  high_cholesterol_00          71263        14.53
301  2014      income_level_00          70675        15.30
302  2014            income_00          70675        15.30
332  2015      income_level_00          78960        17.95
333  2015            income_00          78960        17.95
344  2015  high_cholesterol_00          62409        14.19
365  2016      income_level_00          80340        16.63
366  2016            income_00          80340        16.63
396  2017      income_level_00          74474        16.63
397  2017            income_00          74474        16.63
429  2018      income_level_00          75178        17.31
430  2018            income_00          75178        17.31
460  2019      income_level_00          79066        18.98
461  2019            income_00          79066        18.98
493  2020      income_level_00          78714        19.73
494  2020            income_00          78714        19.73
519  2021               bmi_00          43869        10.03
536  2021  high_cholesterol_00          63487        14.52
552  2022               bmi_00          45103        10.19
566  2022    drinks_alcohol_00          45267        10.23
588  2023      income_level_01          85834        19.88
589  2023            income_01          85834        19.88
600  2023  high_cholesterol_00          54630        12.65
621  2024      income_level_01          85654        18.83
622  2024            income_01          85654        18.83

In [29]:
print("Between 20 to 50 Percent Missing Overview")
missing[missing.missing_pct.between(20, 50)]

Between 20 to 50 Percent Missing Overview

     year              feature  missing_count  missing_pct
18   2005  poor_health_days_00         170482        47.96
51   2006  poor_health_days_00         172876        48.77
82   2007  poor_health_days_00         210488        48.96
115  2008  poor_health_days_00         199528        48.32
146  2009  poor_health_days_00         211705        49.05
179  2010  poor_health_days_00         219988        48.98
210  2011  poor_health_days_00         247464        49.12
243  2012  poor_health_days_00         230368        48.68
274  2013  poor_health_days_00         242192        49.39
338  2015  poor_health_days_00         218430        49.66
371  2016  poor_health_days_00         238734        49.40
402  2017  poor_health_days_00         216070        48.24
435  2018  poor_health_days_00         207954        47.89
466  2019  poor_health_days_00         194349        46.64
524  2021      income_level_01          93524        21.39
525  2021            income_01          93524        21.39
530  2021  poor_health_days_00         209617        47.94
557  2022      income_level_01          94406        21.33
558  2022            income_01          94406        21.33
563  2022  poor_health_days_00         194023        43.83
594  2023  poor_health_days_00         185957        43.07
627  2024  poor_health_days_00         192804        42.40

In [31]:
print("Over 50 Percent Missing Overview")
missing[missing.missing_pct >= 50]

Over 50 Percent Missing Overview

     year               feature  missing_count  missing_pct
22   2005   avg_drinks_p_day_00         182983        51.48
55   2006   avg_drinks_p_day_00         188203        53.09
86   2007   avg_drinks_p_day_00         229206        53.31
119  2008   avg_drinks_p_day_00         220208        53.33
150  2009   avg_drinks_p_day_00         235939        54.66
183  2010   avg_drinks_p_day_00         246348        54.85
214  2011   avg_drinks_p_day_00         265968        52.79
247  2012   avg_drinks_p_day_00         248055        52.42
278  2013   avg_drinks_p_day_00         259761        52.97
307  2014   poor_health_days_00         231960        50.22
311  2014   avg_drinks_p_day_00         247374        53.56
342  2015   avg_drinks_p_day_00         233306        53.04
375  2016   avg_drinks_p_day_00         251728        52.09
406  2017   avg_drinks_p_day_00         232003        51.79
439  2018   avg_drinks_p_day_00         226073        52.06
470  2019   avg_drinks_p_day_00         222153        53.32
499  2020   poor_health_days_00         203131        50.90
503  2020   avg_drinks_p_day_00         212512        53.25
534  2021   avg_drinks_p_day_00         230768        52.78
567  2022   avg_drinks_p_day_00         235426        53.18
598  2023   avg_drinks_p_day_00         222488        51.53
620  2024  employment_status_00         454774       100.00
631  2024   avg_drinks_p_day_00         247801        54.49

## Diabetes classes and feature availability

In [13]:
diabetes = categories[categories["feature"] == "diabetes"]
counts = diabetes.pivot(index="year", columns="value", values="count").fillna(0).astype(int)
print("Diabetes class counts:")
display(counts)
print("Diabetes class percentages:")
display(counts.div(overview.set_index("year")["rows"], axis=0).mul(100).round(2))

# Presence checks whether a column exists, independently of its missing rate.
all_features = sorted(set().union(*columns_by_year.values()))
presence = pd.DataFrame({year: [feature in columns_by_year[year]
                                for feature in all_features]
                         for year in years}, index=all_features)
print("Features not present in every year:")
display(presence.loc[~presence.all(axis=1)].replace({True: "Yes", False: "No"}))

Diabetes class counts:

value  Diabetic  Non-diabetic  Pre-diabetic
year
2005      33317        318276          3853
2006      36080        313988          4429
2007      48068        375981          5893
2008      47391        360053          5454
2009      52381        372446          6809
2010      57464        384063          7629
2011      62456        433212          8178
2012      59749        405759          7735
2013      62341        419431          8596
2014      61099        393112          7668
2015      57249        374942          7690
2016      66025        408348          8857
2017      60339        379399          8214
2018      60577        365403          8252
2019      57383        350129          9149
2020      52061        338378          8611
2021      57608        369701          9941
2022      61133        371209         10328
2023      59736        361416         10594
2024      65765        377703         11306

Diabetes class percentages:

value  Diabetic  Non-diabetic  Pre-diabetic
year
2005       9.37         89.54          1.08
2006      10.18         88.57          1.25
2007      11.18         87.45          1.37
2008      11.48         87.20          1.32
2009      12.14         86.29          1.58
2010      12.79         85.51          1.70
2011      12.40         85.98          1.62
2012      12.63         85.74          1.63
2013      12.71         85.53          1.75
2014      13.23         85.11          1.66
2015      13.01         85.24          1.75
2016      13.66         84.50          1.83
2017      13.47         84.70          1.83
2018      13.95         84.15          1.90
2019      13.77         84.03          2.20
2020      13.05         84.80          2.16
2021      13.18         84.55          2.27
2022      13.81         83.86          2.33
2023      13.84         83.71          2.45
2024      14.46         83.05          2.49

Features not present in every year:

,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
high_bp_00,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No
high_cholesterol_00,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No
income_00,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No
income_01,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes
income_level_00,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No
income_level_01,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes

## Inspect features

In [33]:
focus = ["employment_status_00", "avg_drinks_p_day_00", "poor_health_days_00",
         "bmi_00", "race_00", "income_00", "income_01",
         "high_bp_00", "high_cholesterol_00"]
missing_table = missing.pivot(index="feature", columns="year", values="missing_pct")
display(missing_table.reindex(focus))

def show_categories(feature, selected_years):
    return categories[(categories["feature"] == feature) &
                      (categories["year"].isin(selected_years))][
                          ["year", "value", "count"]].sort_values(["year", "value"])

print("Income categories, 2020–2021:")
display(show_categories("income_00", [2020, 2021]))
display(show_categories("income_01", [2020, 2021]))
print("Race categories, 2021–2023:")
display(show_categories("race_00", [2021, 2022, 2023]))
print("Employment, 2023–2024:")
display(show_categories("employment_status_00", [2023, 2024]))
print("Personal doctor, 2020–2022:")
display(show_categories("has_personal_doctor_00", [2020, 2021, 2022]))
print("High BP and cholesterol availability:")
display(presence.loc[["high_bp_00", "high_cholesterol_00"]]
        .replace({True: "Yes", False: "No"}))

year,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
feature,,,,,,,,,,,,,,,,,,,,
employment_status_00,0.29,0.33,0.36,0.38,0.44,0.50,0.51,0.54,0.68,1.06,0.85,0.81,0.81,1.11,1.51,1.68,1.82,2.40,1.73,100.00
avg_drinks_p_day_00,51.48,53.09,53.31,53.33,54.66,54.85,52.79,52.42,52.97,53.56,53.04,52.09,51.79,52.06,53.32,53.25,52.78,53.18,51.53,54.49
poor_health_days_00,47.96,48.77,48.96,48.32,49.05,48.98,49.12,48.68,49.39,50.22,49.66,49.40,48.24,47.89,46.64,50.90,47.94,43.83,43.07,42.40
bmi_00,4.60,4.90,4.60,4.49,4.57,4.73,4.84,4.75,4.80,6.00,7.66,7.54,7.49,7.43,8.06,9.55,10.03,10.19,8.77,8.59
race_00,0.96,1.06,0.98,1.05,1.10,1.41,1.20,1.31,1.73,1.69,1.67,1.77,1.93,1.91,2.10,2.20,2.45,3.11,2.17,1.96
income_00,13.68,14.03,13.69,12.95,13.52,14.29,14.53,14.02,14.48,15.30,17.95,16.63,16.63,17.31,18.98,19.73,NaN,NaN,NaN,NaN
income_01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.39,21.33,19.88,18.83
high_bp_00,0.16,NaN,0.18,NaN,0.20,NaN,0.26,NaN,0.27,NaN,0.29,NaN,0.28,NaN,0.34,NaN,0.38,NaN,0.40,NaN
high_cholesterol_00,18.67,NaN,15.61,NaN,13.57,NaN,14.67,NaN,14.53,NaN,14.19,NaN,7.05,NaN,6.91,NaN,14.52,NaN,12.65,NaN

Income categories, 2020–2021:

     year      value   count
712  2020        1.0   12865
711  2020        2.0   13669
710  2020        3.0   20993
709  2020        4.0   27649
708  2020        5.0   31346
707  2020        6.0   43771
706  2020        7.0   52381
704  2020        8.0  117662
705  2020  <missing>   78714

     year      value  count
758  2021        1.0  10840
754  2021       10.0  19744
755  2021       11.0  18924
757  2021        2.0  11501
756  2021        3.0  14916
753  2021        4.0  21016
752  2021        5.0  43803
749  2021        6.0  48277
748  2021        7.0  59346
750  2021        8.0  47787
751  2021        9.0  47572
747  2021  <missing>  93524

Race categories, 2021–2023:

     year                                      value   count
775  2021                                  <missing>   10709
779  2021          American Indian or Alaskan Native    1982
777  2021                                      Asian    7246
773  2021                                      Black   32695
772  2021                                   Hispanic   38268
776  2021                                Multiracial    9213
774  2021  Native Hawaiian or other Pacific Islander   11369
778  2021                                      Other    3920
771  2021                                      White  321848
830  2022                                  <missing>   13775
834  2022          American Indian or Alaskan Native    2402
833  2022                                      Asian    6927
829  2022                                      Black   35333
828  2022                                   Hispanic   42729
832  2022                                Multiracial    9545
831  2022  Native Hawaiian or other Pacific Islander   13267
827  2022                                      White  318692
880  2023                                  <missing>    9377
883  2023          American Indian or Alaskan Native    2088
881  2023                                      Asian    6775
877  2023                                      Black   32757
876  2023                                   Hispanic   43141
879  2023                                Multiracial   10091
878  2023  Native Hawaiian or other Pacific Islander   12036
882  2023                                      Other    3338
875  2023                                      White  312143

Employment, 2023–2024:

     year                             value   count
892  2023                         <missing>    7473
888  2023                       A homemaker   17479
889  2023                         A student   10206
884  2023                Employed for wages  177312
890  2023  Out of work for less that 1 year    8947
891  2023  Out of work for more than 1 year    7631
885  2023                           Retired  139497
886  2023                     Self-employed   37841
887  2023                    Unable to work   25360
940  2024                         <missing>  454774

Personal doctor, 2020–2022:

     year          value   count
743  2020      <missing>    1991
742  2020  More than one   27173
741  2020             No   69783
740  2020  Yes, only one  300103
792  2021      <missing>    3572
790  2021  More than one  123975
791  2021             No   52551
789  2021  Yes, only one  257152
847  2022      <missing>    4249
845  2022  More than one  136075
846  2022             No   56862
844  2022  Yes, only one  245484

High BP and cholesterol availability:

,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
high_bp_00,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No
high_cholesterol_00,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No,Yes,No